### ISSUE TITLE
While using plugin for ios not work as expected.

### ISSUE THREAD

**Issue by DeveloperHitesh** [Amphiluke/cordova-plugin-save-dialog#3] opened 2023-04-24 07:21 UTC
I use this plugin for download pdf file. 
When i try to execute flow on android device at the same time saveDialog window appear and able to download specified file.

Simmilar way while i'm trying to do on ios device that time no any window appear on screen, whenever I logout from application then it comes window and able to download.

Anyone can look into it and anything related to same issue face and provide solution it would help.

Thanks in advace.

Sample code
=======================================================
 let blob = new Blob([this.fileData], { type: "application/pdf" });

	cordova.plugins.saveDialog.saveFile(blob, fileName).then(uri => {
		console.info("The file has been successfully saved to", uri);
    }).catch(reason => {
          console.warn(reason);
    });

====================================================
Above code is same for android as well as ios.
fileData is blob data and is valid , working for android

**Comment by Amphiluke** [comment] 2023-04-24 15:03
Hi, @DeveloperHitesh 

It’s pretty hard to tell what goes wrong based on the provided information. Do I understand correctly that the Save dialog doesn’t show until you log out from your application? If so, it’s extremely strange because the plugin’s functionality has nothing related to authorization or something like that…

Did you try to debug your app in Xcode? There could also be some errors/warnings in the debug logs that shed light on the cause of the problem. Are you able to reproduce the issue on a bare minimal Cordova project (with no other plugins installed except for this one)? If no, try removing other plugins one by one from your project until the bug goes away. This way you can find which plugin conflicts with or breaks the Save dialog functionality.

**Comment by DeveloperHitesh** [comment] 2023-04-24 15:19
> 
Do I understand correctly that the Save dialog doesn’t show until you log out from your application?
Yes, when i logout from application then save dialog shows. I'll check more on logs and try to  remove other cordova plugins and update you on same.

**Comment by Amphiluke** [comment] 2023-05-28 05:41
Closing this issue now. Feel free to reopen if you get some details revealing the root of the evil, or if you are able to provide steps to reproduce the issue on a a bare minimal Cordova project.

**Closed as completed by Amphiluke** 2023-05-28 05:41 UTC
